// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ESP_SmartPrognostics
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Motor_ID")]
            public string Motor_ID { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Cycle")]
            public float Cycle { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Current_A")]
            public float Current_A { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Vibration_RMS")]
            public float Vibration_RMS { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Temperature_C")]
            public float Temperature_C { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Pressure_PSI")]
            public float Pressure_PSI { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Health_Index")]
            public float Health_Index { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Remaining_Life")]
            public float Remaining_Life { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Motor_ID")]
            public float[] Motor_ID { get; set; }

            [ColumnName(@"Cycle")]
            public float Cycle { get; set; }

            [ColumnName(@"Current_A")]
            public float Current_A { get; set; }

            [ColumnName(@"Vibration_RMS")]
            public float Vibration_RMS { get; set; }

            [ColumnName(@"Temperature_C")]
            public float Temperature_C { get; set; }

            [ColumnName(@"Pressure_PSI")]
            public float Pressure_PSI { get; set; }

            [ColumnName(@"Health_Index")]
            public float Health_Index { get; set; }

            [ColumnName(@"Remaining_Life")]
            public float Remaining_Life { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
